import type { Assignment } from './types'

export const assignments: Assignment[] = [
  {
    id: 1,
    eyebrow: 'Bài tập 1 · Mục 1.4',
    title: 'Bài 1 - Bài tập 1 của mục 1.4: Thao tác cơ bản với tệp tin và thư mục',
    shortTitle: 'Tệp tin & thư mục',
    description: 'Trình bày cấu trúc thư mục tối ưu và quy tắc đặt tên tệp đã thiết lập, kèm ảnh chụp minh họa.',
    objective: 'Thiết lập một hệ thống thư mục dễ tìm, nhất quán và an toàn; sử dụng thành thạo tạo mới, sao chép, di chuyển, đổi tên, xóa và khôi phục dữ liệu.',
    process: ['Tạo cấu trúc thư mục theo học phần và tuần học.', 'Đặt tên tệp rõ nghĩa, không dùng tên chung chung.', 'Thực hành sao chép, di chuyển, xóa và khôi phục từ Recycle Bin.'],
    lesson: 'Một cấu trúc lưu trữ tốt giúp mình tiết kiệm thời gian, giảm nhầm lẫn và chủ động hơn khi làm việc với nhiều tài liệu học tập.',
    skills: ['Quản lý dữ liệu', 'Tổ chức tệp', 'An toàn thông tin'],
    pageCount: 9,
    color: '#ffd8a8',
  },
  {
    id: 2,
    eyebrow: 'Bài tập 2 · Mục 2.4',
    title: 'Bài 2 - Bài tập 2 của mục 2.4: Tìm kiếm và đánh giá thông tin học thuật',
    shortTitle: 'Thông tin học thuật',
    description: 'Trình bày kết quả tìm kiếm học thuật bằng các toán tử nâng cao và bảng đánh giá nguồn tin đã thực hiện.',
    objective: 'Rèn khả năng dùng từ khóa và toán tử tìm kiếm nâng cao, đồng thời đánh giá độ tin cậy, tính cập nhật và giá trị học thuật của nguồn tin.',
    process: ['Xác định chủ đề ứng dụng AI trong học tiếng Hàn và xây dựng bộ từ khóa phù hợp.', 'Thu thập, hệ thống hóa 11 nguồn học thuật và nguồn chuyên môn.', 'Đối chiếu tác giả, cơ quan xuất bản, phương pháp, trích dẫn, tính cập nhật và mức độ liên quan.'],
    lesson: 'Kết quả tìm kiếm đầu tiên chưa chắc là nguồn tốt nhất. Mình cần đọc có mục đích, kiểm tra bằng chứng và đối chiếu nhiều nguồn trước khi sử dụng.',
    skills: ['Tìm kiếm nâng cao', 'Đánh giá nguồn', 'Tư duy phản biện'],
    pageCount: 6,
    color: '#d7e9de',
  },
  {
    id: 3,
    eyebrow: 'Bài tập 3 · Mục 3.4',
    title: 'Bài 3 - Bài tập 2 của mục 3.4: Viết Prompt hiệu quả cho các tác vụ học tập',
    shortTitle: 'Prompt hiệu quả',
    description: 'Trình bày sự so sánh giữa Prompt ban đầu và Prompt cải tiến cùng kết quả đầu ra từ AI.',
    objective: 'Nhận diện những thành phần làm nên một prompt rõ ràng và kiểm chứng tác động của vai trò, bối cảnh, yêu cầu đầu ra và tiêu chí chất lượng.',
    process: ['Viết prompt ban đầu cho từng tác vụ.', 'Bổ sung vai trò, ngữ cảnh, cấu trúc và giới hạn.', 'So sánh đầu ra, chỉ ra điểm mạnh và phần cần chỉnh sửa.'],
    lesson: 'Prompt tốt không chỉ là câu lệnh dài. Điều quan trọng là mục tiêu rõ, bối cảnh đủ và tiêu chí đầu ra có thể kiểm tra được.',
    skills: ['Prompt engineering', 'Phân tích đầu ra', 'Học tập với AI'],
    pageCount: 10,
    color: '#f6dce7',
  },
  {
    id: 4,
    eyebrow: 'Bài tập 4 · Mục 4.4',
    title: 'Bài 4 - Bài tập 3 của mục 4.4: Sử dụng công cụ hợp tác trực tuyến cho dự án nhóm',
    shortTitle: 'Hợp tác trực tuyến',
    description: 'Trình bày minh chứng về việc sử dụng công cụ quản lý dự án nhóm và cách thức phối hợp trực tuyến.',
    objective: 'Biết phân công, theo dõi tiến độ, đồng biên tập tài liệu và trao đổi trực tuyến một cách minh bạch, nhất quán.',
    process: ['Quản lý nhiệm vụ và tiến độ chung bằng Google Sheets.', 'Đồng biên tập trên Google Docs, lưu trữ và chia sẻ tệp qua Google Drive.', 'Duy trì trao đổi, họp và phản hồi nhóm trên Microsoft Teams.'],
    lesson: 'Công cụ chỉ phát huy hiệu quả khi nhóm có quy ước rõ ràng. Giao tiếp chủ động, trách nhiệm cá nhân và cập nhật tiến độ là ba yếu tố giữ dự án đi đúng hướng.',
    skills: ['Làm việc nhóm', 'Quản trị dự án', 'Giao tiếp số'],
    pageCount: 5,
    color: '#cfe4f5',
  },
  {
    id: 5,
    eyebrow: 'Bài tập 5 · Mục 5.4',
    title: 'Bài 5 - Bài tập 2 của mục 5.4: Sử dụng AI tạo sinh để hỗ trợ sáng tạo nội dung',
    shortTitle: 'AI tạo sinh',
    description: 'Trưng bày sản phẩm nội dung số hoàn thiện (hình ảnh, video hoặc bài viết) được hỗ trợ bởi AI.',
    objective: 'Kết hợp nhiều công cụ AI để hình thành ý tưởng, tạo hình ảnh và hoàn thiện một sản phẩm nội dung số có chủ đích.',
    process: ['Dùng Gemini xây dựng ý tưởng và cấu trúc nội dung.', 'Tạo tư liệu hình ảnh bằng DALL·E.', 'Biên tập lại bố cục, màu sắc và thông điệp trên Canva.'],
    lesson: 'AI giúp tăng tốc quá trình sáng tạo, nhưng chất lượng cuối cùng vẫn phụ thuộc vào lựa chọn, kiểm chứng và khả năng biên tập của con người.',
    skills: ['Sáng tạo nội dung', 'Thiết kế số', 'Phối hợp công cụ AI'],
    pageCount: 7,
    color: '#f3e2b8',
    externalUrl: 'https://canva.link/sunneo66g7f8ofd',
  },
  {
    id: 6,
    eyebrow: 'Bài tập 6 · Mục 6.4',
    title: 'Bài 6 - Bài tập 4 của mục 6.4: Sử dụng AI có trách nhiệm trong học tập và nghiên cứu',
    shortTitle: 'AI có trách nhiệm',
    description: 'Trình bày bộ nguyên tắc cá nhân về sử dụng AI có trách nhiệm dựa trên các nghiên cứu đã thực hiện.',
    objective: 'Hiểu ranh giới giữa hỗ trợ và thay thế, thực hành minh bạch hóa việc dùng AI, trích dẫn phù hợp và bảo vệ dữ liệu cá nhân.',
    process: ['Tìm hiểu quy định và nguyên tắc sử dụng AI trong học thuật.', 'Ứng dụng AI để hỗ trợ lập dàn ý nghiên cứu.', 'Kiểm chứng, chỉnh sửa, ghi nhận công cụ và chịu trách nhiệm với sản phẩm.'],
    lesson: 'Sử dụng AI có trách nhiệm là biết mình đang nhờ AI làm gì, kiểm tra kết quả ra sao và luôn giữ quyền quyết định học thuật ở chính mình.',
    skills: ['Liêm chính học thuật', 'Đạo đức AI', 'Bảo mật dữ liệu'],
    pageCount: 5,
    color: '#e6ddf2',
  },
]
